import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class IndexService {

  data = [{quantity: "3", symbol: "ADBE", color: "#d60000", tags: [{name: "Tech"}, {name: "Growth"}]},
    {symbol: "AMZN", color: "#15ade0", quantity: "3", tags: [{name: "My custom tag"}]},
    {symbol: "BA", quantity: "8", tags: [{name: "Aerospace"}]},
    {symbol: "BAC", quantity: "52", color: "#ffffff", tags: [{name: "Bank"}]},
    {symbol: "FB", color: "#15ade0", quantity: "3", tags: [{name: "Tech"}, {name: "Growth"}]},
    {symbol: "JNJ", quantity: "4", tags: [{name: "My custom tag"}]},
    {symbol: "GOOGL", quantity: "3", tags: [{name: "Tech"}, {name: "Growth"}]},
    {symbol: "JPM", quantity: "12", color: "#7e7e7e", tags: [{name: "Bank"}]},
    {symbol: "BRK.B", color: "#d87c13", quantity: "9", tags: [{name: "My custom tag"}]},
    {symbol: "V", color: "#15ade0", quantity: "9", tags: [{name: "#1"}]},
    {symbol: "TSLA", quantity: "10", color: "#ff0000", tags: [{name: "X Æ A-12"}]}]

  stockTradingData = [
    {
      comment: "valid",
      direction: "BUY",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "NFLX",
      takeprofit: 0,
      timeframe: "D1",
      valid: true
    },
    {
      comment: "Not clear uptrend",
      direction: "SELL",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "OESX",
      takeprofit: 0,
      timeframe: "D1",
      valid: false
    },
    {
      comment: "valid",
      direction: "SELL",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "TESS",
      takeprofit: 0,
      timeframe: "D1",
      valid: true
    },
    {
      comment: "valid",
      direction: "BUY",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "MCD",
      takeprofit: 0,
      timeframe: "D1",
      valid: true
    },
    {
      comment: "valid",
      direction: "BUY",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "TSLA",
      takeprofit: 0,
      timeframe: "D1",
      valid: true
    },
    {
      comment: "50 EMA < 200 SMA",
      direction: "BUY",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "HTZ",
      takeprofit: 0,
      timeframe: "D1",
      valid: false
    },
    {
      comment: "valid",
      direction: "SELL",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "TESS",
      takeprofit: 0,
      timeframe: "D1",
      valid: true
    },
    {
      comment: "valid",
      direction: "BUY",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "TESS",
      takeprofit: 0,
      timeframe: "D1",
      valid: true
    },
    {
      comment: "valid",
      direction: "SELL",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "TESS",
      takeprofit: 0,
      timeframe: "D1",
      valid: false
    },
    {
      comment: "valid",
      direction: "SELL",
      entrydate: {seconds: 1590479880, nanoseconds: 0},
      entryprice: 4.8789,
      exitdate: {seconds: 1591083000, nanoseconds: 0},
      exitprice: 5.03,
      outcome: "WIN",
      profit: 7.81,
      quantity: 65,
      riskreward: 0,
      stoploss: 0,
      strategy: "Range",
      symbol: "TESS",
      takeprofit: 0,
      timeframe: "D1",
      valid: true
    },
  ]

  constructor(private http: HttpClient,) {
  }

}
